Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_dT_profile_figsrc.py", line 270, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_dT_profile_figsrc.py", line 59, in main
    pres, temp, ss_qss, w, z, z_bins = get_case_data(case_label)
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_dT_profile_figsrc.py", line 84, in get_case_data
    case_dir_name = case_label_dict[case_label]
NameError: name 'case_label' is not defined
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_dT_profile_figsrc.py", line 270, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_dT_profile_figsrc.py", line 59, in main
    pres, temp, ss_qss, w, z, z_bins = get_case_data(case_label)
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_dT_profile_figsrc.py", line 87, in get_case_data
    met_file = Dataset(DATA_DIR + case_dir_name + \
NameError: name 'Dataset' is not defined
slurmstepd: error: *** JOB 28390692 ON n0272.lr6 CANCELLED AT 2020-12-27T21:32:24 ***
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_dT_profile_figsrc.py", line 271, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_dT_profile_figsrc.py", line 78, in main
    w_dict['allpts'], z_dict['allpts'], z_bins, 'allpts')
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_dT_profile_figsrc.py", line 153, in make_and_save_dT_profile
    z_bins = z_bins_dict[case_label]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
Polluted allpts
79.1924527409238
Unpolluted allpts
101.41726230327727
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_dT_profile_figsrc.py", line 271, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_dT_profile_figsrc.py", line 78, in main
    w_dict['allpts'], z_dict['allpts'], z_bins_dict, 'allpts')
  File "/global/home/users/kalatimer/proj/20supersat/src/revmywrf/FINAL_dT_profile_figsrc.py", line 185, in make_and_save_dT_profile
    ax2.legend([poll_line, unpoll_line], ['Polluted', 'Unpolluted'])
NameError: name 'ax2' is not defined
/var/spool/slurmd/job28395613/slurm_script: line 2:  4179 Killed                  python $HOME/proj/20supersat/src/revmywrf/FINAL_dT_profile_figsrc.py
slurmstepd: error: Detected 1 oom-kill event(s) in step 28395613.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
Polluted allpts
79.1924527409238
Unpolluted allpts
101.41726230327727
Polluted up10perc
97.89694065064083
Unpolluted up10perc
139.9169740170911
/global/home/users/kalatimer/proj/20supersat/src/revmywrf/ss_qss_calculations.py:72: RuntimeWarning: invalid value encountered in true_divide
  return meanr/nconc
Polluted allpts
79.1924527409238
Unpolluted allpts
101.41726230327727
Polluted up10perc
97.89694065064083
Unpolluted up10perc
139.9169740170911
