Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/check_lwc_in_slice.py", line 51, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/check_lwc_in_slice.py", line 19, in main
    print_avg_lwc_in_slice(case_label)
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/check_lwc_in_slice.py", line 24, in print_avg_lwc_in_slice
    met_file = Dataset(DATA_DIR + case_dir_name + \
NameError: name 'case_dir_name' is not defined
Polluted
0.00129194
0.00129194
Unpolluted
0.0011899032
0.0011899032
