Polluted
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 118, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 34, in main
    make_and_save_lh_cdf(case_label) 
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 81, in make_and_save_lh_cdf
    make_plot_with_radius_marker(imax, lh_cdf, case_label)
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 106, in make_plot_with_radius_marker
    ax.plot([rmax], [lh_cdf[imax]], marker='o', color='black', markersize=5)
IndexError: index 32 is out of bounds for axis 0 with size 32
Unpolluted
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 118, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 34, in main
    make_and_save_lh_cdf(case_label) 
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 81, in make_and_save_lh_cdf
    make_plot_with_radius_marker(imax, lh_cdf, case_label)
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 106, in make_plot_with_radius_marker
    ax.plot([rmax], [lh_cdf[imax]], marker='o', color='black', markersize=5)
IndexError: index 32 is out of bounds for axis 0 with size 32
Polluted
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 124, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 34, in main
    make_and_save_lh_cdf(case_label) 
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 69, in make_and_save_lh_cdf
    lh = lh[filter_inds_with_w]
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/ma/core.py", line 3188, in __getitem__
    dout = self.data[indx]
IndexError: too many indices for array
Unpolluted
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 124, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 34, in main
    make_and_save_lh_cdf(case_label) 
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 69, in make_and_save_lh_cdf
    lh = lh[filter_inds_with_w]
  File "/global/home/users/kalatimer/miniconda3/envs/supersatenv/lib/python3.7/site-packages/numpy/ma/core.py", line 3188, in __getitem__
    dout = self.data[indx]
IndexError: too many indices for array
slurmstepd: error: *** JOB 29615237 ON n0080.lr6 CANCELLED AT 2021-03-23T13:26:59 ***
Polluted
Traceback (most recent call last):
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 123, in <module>
    main()
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 34, in main
    make_and_save_lh_cdf(case_label) 
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 87, in make_and_save_lh_cdf
    make_plot_with_radius_marker(imax, lh_cdf, case_label)
  File "/global/home/users/kalatimer/proj/20supersat/src/wrf/imax_lwc_spectrum_figsrc.py", line 111, in make_plot_with_radius_marker
    ax.plot([rmax], [lh_cdf[imax]], marker='o', color='black', markersize=5)
IndexError: index 32 is out of bounds for axis 0 with size 32
